### ISSUE TITLE
Sample app works incorrectly

### ISSUE THREAD

**Issue by nadein** [InMobi/sdk-sample-code-ios#1]
I've tried to run sample app (both Swift and Obj-C versions) on iOS 10 Simulator and iOS 9 device (iPad Air). App was built successfully and starts on device but then provides no visuals at all - only whit screen. While debugging I find out it calls _-(void)interstitialDidReceiveAd:(IMInterstitial *)interstitial_ method but then reports an error. 
Here is the log I got while experiencing the error: [log.txt](https://bitbucket.org/snippets/sonysun/eBneL)

Also I tried to implement my own test app where I could successfully show ads. But I faced the issue with no delegate callbacks on user being redirected to ad target page.

**Comment by kvaddamani** [comment]
@nadein Thank you for reporting this issue. You can add **-ObjC** to your **other linker flags** setting to resolve this issue. We will update the apps accordingly.

**Comment by nadein** [comment]
@kvaddamani Thank you for your response. It's cool to use your product.

**Comment by kvaddamani** [comment]
@nadein Thank you very much.
