### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by veersr9** [InMobi/sdk-sample-code-ios#25]
If I am giving banner add size according to my view size but ad is not showing . But if I will give it's default size (320x50) then It is showing . 

Can you please tell me what is the issue .

banner = IMBanner(frame: CGRect(x:0, y:0, width:self.adsBgView.frame.size.width, height:50),
                          placementId: INMOBI_BANNER_PLACEMENT);
        banner!.delegate = self;
        banner!.load()
        adsBgView.addSubview(self.banner!);

**Comment by Aman5692** [comment]
Thanks for reporting we will look into the issue.
