### ISSUE TITLE
Error to show Native Ads

### ISSUE THREAD

**Issue by veersr9** [InMobi/sdk-sample-code-ios#26]
Getting this error in all internet networks and Ads not showing 

"Failed to fetch Native ad for placement id: 1569082123037. Status code : 4, error message: The Ad Request timed out waiting for a response from the network. This can be caused due to a bad network connection. Please try again after a few minutes."

**Comment by Aman5692** [comment]
Hi @veersr9, this seems to be an interim issue with the server. Please try again it should get resolved, meanwhile we will look into the issue, thanks for reporting.

**Comment by azadbaljeet** [comment]
InMobi Native failed to load with error : Error Domain=com.inmobi.ads.requeststatus Code=6 "The SDK encountered an internal error." UserInfo={NSLocalizedDescription=The SDK encountered an internal error.} while InterstitialSample is working. Please help us asap. Thanks

**Comment by ZYHshao** [comment]
Error Domain=com.inmobi.ads.requeststatus Code=6 "The SDK encountered an internal error." UserInfo={NSLocalizedDescription=The SDK encountered an internal error.}   How to do resolve it?
