### ISSUE TITLE
Getting this error message

### ISSUE THREAD

**Issue by veersr9** [InMobi/sdk-sample-code-ios#27]
I implemented native ads and it was working fine and displaying ads. But after 2 day I am watching ad is not visible and getting error in console . let me know why it is showing this error message.

[InMobi] Failed to fetch Native ad for placement id: 1565819596375. Status code : 1, error message: Server returned a no-fill. Please try again.

**Comment by Aman5692** [comment]
Hi @veersr9, it seems like the server is returning a no-fill for placement id: 1565819596375. Please connect with partner manager or account manager, who helped you set up the InMobi account. Please report them the issue, they will help you in getting better fills.

**Comment by alishaker** [comment]
i got this one 
"Error Domain=com.inmobi.ads.requeststatus Code=1 "Server returned a no-fill. Please try again." UserInfo={NSLocalizedDescription=Server returned a no-fill. Please try again."

**Comment by saranyu23** [comment]
@alishaker  is this issue resolved and are ads getting dispalyed now ?
