### ISSUE TITLE
Remove UIWebView Text in "INMMoatWebTracker.h" file

### ISSUE THREAD

**Issue by haarj** [InMobi/sdk-sample-code-ios#32]
My app keeps getting a UIWebView reference warning I believe because the text "UIWebView" is located in the "INMMoatWebTracker.h" file. Can you please remove this and release a new version of your iOS SDK?

Much appreciated!

**Comment by haarj** [comment]
Hi You have "UIWebView" text in a bunch of your source files. Please remove or Apple will reject our apps by end of year. Thanks!

**Comment by prabodhprakash** [comment]
Hello, for the same reason, we have decoupled Moat from the mainline SDK. Kindly refer the documentatiom [here](https://support.inmobi.com/monetize/ios-guidelines/)

**Comment by haarj** [comment]
HI @prabodhprakash,

I decoupled Moat but I'm still getting this result when running the following command:
grep -R UIWebView *
Binary file Pods/InMobiSDK/InMobiSDK.framework/InMobiSDK matches

There might be an instance or text somewhere that says "UIWebView". Can you please remove it?

Thanks!
