### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.

### ISSUE THREAD

**Issue by TaoGEe** [InMobi/sdk-sample-code-ios#57]
ios crash rate:
75% 15.6.1
4%15.5.0
1%15.6.0

sdk version:10.0.8

Fatal Exception: NSInternalInconsistencyException Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.

stacktrace:
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x92d1c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  CoreAutoLayout                 0x5000 -[NSISEngine withAutomaticOptimizationDisabled:]
3  CoreAutoLayout                 0x7b7c -[NSISEngine withBehaviors:performModifications:]
4  UIKitCore                      0x2576e4 -[UIView(Hierarchy) _postMovedFromSuperview:]
5  UIKitCore                      0x18d274 __UIViewWasRemovedFromSuperview
6  UIKitCore                      0x19e508 -[UIView(Hierarchy) removeFromSuperview]
7  WebKit                         0x33ec30 -[WKWebView(WKViewInternalIOS) removeFromSuperview]
8  DiamondSpin                    0xaddaa0 -[IMCustomLandingPageProcessor closeOriginalLandingPage]
9  DiamondSpin                    0xade378 -[IMCustomLandingPageProcessor dealloc]
10 DiamondSpin                    0xb38d14 -[IMAdUnit .cxx_destruct]
11 libobjc.A.dylib                0x77d0 object_cxxDestructFromClass(objc_object*, objc_class*)
12 libobjc.A.dylib                0x4858 objc_destructInstance
13 libobjc.A.dylib                0xd7d4 _objc_rootDealloc
14 DiamondSpin                    0xb3856c -[IMAdUnit dealloc]
15 CoreFoundation                 0x467d4 -[__NSArrayI_Transfer dealloc]
16 libobjc.A.dylib                0x6e58 AutoreleasePoolPage::releaseUntil(objc_object**)
17 libobjc.A.dylib                0x3704 objc_autoreleasePoolPop
18 libdispatch.dylib              0xa750 _dispatch_lane_serial_drain$VARIANT$mp
19 libdispatch.dylib              0xb224 _dispatch_lane_invoke$VARIANT$mp
20 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread
21 libsystem_pthread.dylib        0x1e10 _pthread_wqthread
22 libsystem_pthread.dylib        0x193c start_wqthread

**Comment by kshtgarg21** [comment]
This is fixed as part of IOS SDK 10.1.1
